---

- name: Install Emacs
  homebrew_cask: 
    name: emacs 
    state: present
    install_options: 'appdir=/Applications' 

- name: Clone Spacemacs repository
  git: 
    repo: "{{ spacemacs_repository }}" 
    version: "{{ spacemacs_branch }}" 
    dest: "{{ ansible_user_dir }}/.emacs.d" 
    depth: 1

- name: Render .spacemacs template
  template: 
    src: "{{ dot_spacemacs_template_path }}" 
    dest: "{{ ansible_user_dir }}/.spacemacs"
